[package]
name = "hashtable_shm_server"
version.workspace = true
edition.workspace = true



[dependencies]
hashtable_shm.workspace = true
clap.workspace = true
libc.workspace = true
rustix.workspace = true
thiserror.workspace = true
ctrlc.workspace = true